# Data Preparation

Clean the data here, once, and export as a csv for analysis.

In [29]:
# import libraries
import pandas as pd
import numpy as np

In [7]:
# import data
df_city = pd.read_csv('../../data/processed/grid/bal/2018-09-23_var/bal_data_500.csv')

In [47]:
df.describe()

x              y           area  lst_day_mean  lst_day_max  \
count     873.000000     873.000000     873.000000    873.000000   873.000000   
mean   433071.780346  182388.614704  239612.992222     42.033448    46.101818   
std      4470.021231    4401.682579   33375.791984      4.049121     2.888918   
min    424996.178971  170212.211496     354.092810     22.807793    23.720533   
25%    429496.178971  179212.211496  250000.000000     40.376811    44.287132   
50%    432996.178971  182712.211496  250000.000000     42.750324    46.201408   
75%    436996.178971  186212.211496  250000.000000     44.792342    47.961624   
max    440496.178971  189212.211496  250000.000000     49.151763    58.582375   

       lst_day_min  lst_day_var  lst_night_mean  lst_night_max  lst_night_min  \
count   873.000000   873.000000      873.000000     873.000000     873.000000   
mean     35.045417    10.184243       28.973201      30.813984      24.428318   
std       6.865318    14.376319        1.927107       1.316732       4.348771   
min      19.782183     0.094168       20.526812      23.204323      16.375092   
25%      29.051159     1.340961       28.445516      29.841621      20.443888   
50%      32.237560     3.901684       29.310599      30.688068      21.589033   
75%      41.583397    14.698405       30.168775      31.529123      28.821945   
max      47.422459    94.761294       32.778806      35.316219      31.341824   

          ...       svf_min_sl  svf_var_sl  dsm_mean_sl  dsm_max_sl  \
count     ...       873.000000  873.000000   873.000000  873.000000   
mean      ...         0.525054    0.004235    61.441671   92.276754   
std       ...         0.109578    0.003037    41.666641   41.932075   
min       ...         0.115733    0.000547     2.792569   22.861799   
25%       ...         0.457870    0.002480    22.794995   53.088501   
50%       ...         0.533105    0.003472    55.825839   87.651879   
75%       ...         0.596182    0.005182    96.605942  129.902777   
max       ...         0.804769    0.026131   143.426654  176.591482   

       dsm_min_sl  dsm_var_sl  elev_mean_sl  elev_max_sl  elev_min_sl  \
count  873.000000  873.000000    873.000000   873.000000   873.000000   
mean    46.173275   58.079479     58.495292    69.815675    46.977901   
std     38.971040   45.820298     41.339051    42.451143    38.958348   
min     -7.290245    5.768982      1.232402     3.813496    -0.631487   
25%     10.066744   32.096592     20.150378    31.241457    11.026321   
50%     40.203563   43.486246     52.851992    64.040571    41.181864   
75%     76.076421   62.236969     92.945271   109.241575    77.085647   
max    134.702774  288.939178    140.895922   146.305188   135.038254   

       elev_var_sl  
count   873.000000  
mean     39.309474  
std      39.665628  
min       0.952709  
25%      16.381232  
50%      27.766738  
75%      44.130840  
max     269.000551  

[8 rows x 119 columns]

### > List the data

In [33]:
# list of the variables
df_city.columns.values

array(['x', 'y', 'area', 'city', 'lst_day_mean', 'lst_day_max',
       'lst_day_min', 'lst_day_var', 'lst_night_mean', 'lst_night_max',
       'lst_night_min', 'lst_night_var', 'alb_mean', 'alb_max', 'alb_min',
       'alb_var', 'ndvi_mean', 'ndvi_max', 'ndvi_min', 'ndvi_var',
       'lcov_11', 'lcov_21', 'lcov_22', 'lcov_23', 'lcov_24', 'lcov_31',
       'lcov_41', 'lcov_42', 'lcov_43', 'lcov_52', 'lcov_71', 'lcov_90',
       'lcov_95', 'tree_mean', 'tree_max', 'tree_min', 'tree_var',
       'imp_mean', 'imp_max', 'imp_min', 'imp_var', 'nbdi_mean',
       'nbdi_max', 'nbdi_min', 'nbdi_var', 'pop_dens', 'bldg', 'ntl_mean',
       'ntl_max', 'ntl_min', 'svf_mean', 'svf_max', 'svf_min', 'svf_var',
       'dsm_mean', 'dsm_max', 'dsm_min', 'dsm_var', 'elev_mean',
       'elev_max', 'elev_min', 'elev_var', 'lst_day_mean_sl',
       'lst_day_max_sl', 'lst_day_min_sl', 'lst_day_var_sl',
       'lst_night_mean_sl', 'lst_night_max_sl', 'lst_night_min_sl',
       'lst_night_var_sl', 'alb_mean_sl

# Drop admin variables and rows which are outside of the city limits

In [41]:
# admin variables
df = df.drop(['Unnamed: 0', 'cId'], axis = 1)
# outside city limits
df = df[df['area'] > 0]

# Drop variables with too many NaNs

Dropping `ntl` night time light variance as there is too little variation in the data - so it's NaN.
Keeping the `_sl` variables with 2% NaN. They could be removed, but also might be useful. So the question is do we drop the row or the column during analysis?

In [46]:
# what % of data is NaN?
((len(df) - df.count() ) / len(df)).sort_values(ascending=False)[0:30]

elev_var_sl    0.0
elev_min_sl    0.0
lcov_90        0.0
lcov_95        0.0
tree_mean      0.0
tree_max       0.0
tree_min       0.0
tree_var       0.0
imp_mean       0.0
imp_max        0.0
imp_min        0.0
imp_var        0.0
nbdi_mean      0.0
nbdi_max       0.0
nbdi_min       0.0
nbdi_var       0.0
pop_dens       0.0
bldg           0.0
ntl_mean       0.0
ntl_max        0.0
ntl_min        0.0
svf_mean       0.0
svf_max        0.0
svf_min        0.0
svf_var        0.0
dsm_mean       0.0
dsm_max        0.0
dsm_min        0.0
dsm_var        0.0
lcov_71        0.0
dtype: float64

Drop `ntl_var`

In [43]:
df = df.drop(['ntl_var','ntl_var_sl'], axis=1)

Drop NaN rows and columns (shouldn't be any)

# Land cover

In [8]:
vars_all = df_city.columns.values
vars_all = df_city.columns.values

### ADMIN ###
df_city = df_city.drop(['Unnamed: 0', 'cId'], axis = 1)
# outside city limits
df_city = df_city[df_city['area'] > 0]

### NaN variables
# remove night time lights (not enough variance to get standard deviation)
df_city = df_city.drop(['ntl_var','ntl_var_sl'], axis=1)
# drop any nan rows and report how many dropped
df_city = df_city.dropna(axis=0, how='any')

In [14]:
vars_elev = [i for i in vars_all if 'elev' in i]
# remove sd vars
vars_elev = [x for x in vars_elev if 'var' not in x]
# calculate the mean of each
elev_means = df_city[vars_elev].mean(axis=0)

Turn the landcover variables into a percentage of the grid cell

In [15]:
elev_means

elev_mean       58.650585
elev_max        70.009919
elev_min        47.061185
elev_mean_sl    58.495292
elev_max_sl     69.815675
elev_min_sl     46.977901
dtype: float64

In [16]:
df_city[vars_elev].head()

elev_mean    elev_max    elev_min  elev_mean_sl  elev_max_sl  elev_min_sl
0  141.196590  148.020615  136.969772    139.606597   145.219447   133.393799
1  139.150631  143.034424  134.510712    137.912241   144.255893   131.701286
2  138.459692  141.588562  133.347183    133.755894   140.949216   126.962926
3  136.670537  140.964447  133.251160    131.290824   137.672006   122.528197
4  130.393947  134.772583  124.124527    128.647962   135.464316   119.184160

In [18]:
df_city[vars_elev] = df[vars_elev] - elev_means

In [19]:
df_city[vars_elev].head()

elev_mean   elev_max   elev_min  elev_mean_sl  elev_max_sl  elev_min_sl
0  82.546005  78.010696  89.908588     81.111306    75.403772    86.415898
1  80.500046  73.024505  87.449527     79.416949    74.440218    84.723385
2  79.809107  71.578643  86.285999     75.260602    71.133541    79.985025
3  78.019952  70.954528  86.189975     72.795532    67.856331    75.550296
4  71.743362  64.762664  77.063342     70.152670    65.648641    72.206259

Drop cells with water more than 20% of area

In [25]:
vars_lst = [i for i in vars_all if 'lst' in i]
# remove sd vars
vars_lst = [x for x in vars_lst if 'sd' not in x]
# calculate the mean of each
lst_means = df_city[vars_lst].mean(axis=0)
# df_city[vars_lst] = df[vars_lst] - lst_means

In [26]:
vars_lst

['lst_day_mean',
 'lst_day_max',
 'lst_day_min',
 'lst_day_var',
 'lst_night_mean',
 'lst_night_max',
 'lst_night_min',
 'lst_night_var',
 'lst_day_mean_sl',
 'lst_day_max_sl',
 'lst_day_min_sl',
 'lst_day_var_sl',
 'lst_night_mean_sl',
 'lst_night_max_sl',
 'lst_night_min_sl',
 'lst_night_var_sl']

In [27]:
df = df_city.copy()

In [30]:
vars_lcov = [i for i in vars_all if 'lcov' in i]
# set other NaN landcover values to 0
df[vars_lcov] = df[vars_lcov].fillna(0)
# calculate the max area of a cell
area_max = np.max([np.max(df[i]) for i in vars_lcov])
# divide these values by the area value
df = df[df['area'] > 0]

In [31]:
area_max

260100.0

In [40]:
df.bldg = (df.bldg - np.min(df.bldg)) / (np.max(df.bldg) - np.min(df.bldg))


In [42]:
df.bldg.describe()

count    873.000000
mean       0.295389
std        0.185791
min        0.000000
25%        0.162846
50%        0.277531
75%        0.380669
max        1.000000
Name: bldg, dtype: float64

Drop the land cover variables that aren't water (they're used in calculating LST)

In [44]:
elev_max = np.max(df[vars_elev].values.max())
elev_max

95.26559754643343

# Tree canopy

In [45]:
df.tree_mean

0       22.691176
1       22.252595
2       22.003460
3       22.533088
4       24.937716
5       22.903114
6       23.319853
7       25.941176
8       31.335640
9       31.341912
10      25.356401
11      31.941176
12      30.069853
13      26.287197
14      21.806228
15      27.485294
16      22.290657
17      23.235294
18      22.573529
19      23.124567
20      22.446367
21      21.897059
22      29.325260
23      22.733564
24      23.786765
25      22.391003
26      22.221453
27      21.952206
28      22.245675
29      22.294118
          ...    
1013    22.911765
1014    25.134948
1015    22.788927
1016    23.599265
1017    23.411765
1042    25.082031
1043    23.209559
1044    22.790441
1045    22.875000
1046    22.805147
1075    22.121107
1076    23.553633
1077    22.886029
1078    23.667820
1108    24.605536
1109    21.911765
1145    23.639706
1146    25.158088
1147    27.546875
1177    22.363322
1178    22.761246
1179    23.216912
1180    24.577855
1181    26.262976
1210    23

In [ ]:
# make tree values a percentage
vars_tree = [i for i in vars_all if 'tree' in i]
df.loc[:,vars_tree] = df[vars_tree]/100

In [55]:
pd.set_option("display.max_columns",125)

In [57]:
df.describe()

x              y           area  lst_day_mean  lst_day_max  \
count     873.000000     873.000000     873.000000    873.000000   873.000000   
mean   433071.780346  182388.614704  239612.992222     42.033448    46.101818   
std      4470.021231    4401.682579   33375.791984      4.049121     2.888918   
min    424996.178971  170212.211496     354.092810     22.807793    23.720533   
25%    429496.178971  179212.211496  250000.000000     40.376811    44.287132   
50%    432996.178971  182712.211496  250000.000000     42.750324    46.201408   
75%    436996.178971  186212.211496  250000.000000     44.792342    47.961624   
max    440496.178971  189212.211496  250000.000000     49.151763    58.582375   

       lst_day_min  lst_day_var  lst_night_mean  lst_night_max  lst_night_min  \
count   873.000000   873.000000      873.000000     873.000000     873.000000   
mean     35.045417    10.184243       28.973201      30.813984      24.428318   
std       6.865318    14.376319        1.927107       1.316732       4.348771   
min      19.782183     0.094168       20.526812      23.204323      16.375092   
25%      29.051159     1.340961       28.445516      29.841621      20.443888   
50%      32.237560     3.901684       29.310599      30.688068      21.589033   
75%      41.583397    14.698405       30.168775      31.529123      28.821945   
max      47.422459    94.761294       32.778806      35.316219      31.341824   

       lst_night_var    alb_mean     alb_max     alb_min      alb_var  \
count     873.000000  873.000000  873.000000  873.000000   873.000000   
mean        4.296897   68.429449  119.765915   52.070684   170.212147   
std         6.001098   10.220239   43.302819    4.523919   256.969410   
min         0.007023   48.261267   52.757591   42.460239     1.017937   
25%         0.182424   61.353584   85.621994   49.077526    43.717126   
50%         1.157738   66.653878  108.479103   51.232098    85.425008   
75%         6.582554   74.121284  143.260162   54.302074   187.364346   
max        32.864295  133.089308  339.167206   83.493118  3514.015121   

        ndvi_mean    ndvi_max    ndvi_min    ndvi_var        lcov_11  \
count  873.000000  873.000000  873.000000  873.000000     873.000000   
mean     0.268630    0.471214    0.083868    0.008466    5281.443299   
std      0.109675    0.077511    0.082195    0.006036   26320.648036   
min     -0.038006   -0.018424   -0.102680    0.000076       0.000000   
25%      0.186408    0.450032    0.034006    0.004069       0.000000   
50%      0.287323    0.494912    0.062113    0.007067       0.000000   
75%      0.348725    0.521029    0.126145    0.011344       0.000000   
max      0.498488    0.574188    0.445926    0.047394  260100.000000   

             lcov_21        lcov_22        lcov_23        lcov_24  \
count     873.000000     873.000000     873.000000     873.000000   
mean    49905.154639   61989.690722   63267.010309   50963.917526   
std     45923.814139   49299.080318   44177.426231   65003.409697   
min         0.000000       0.000000       0.000000       0.000000   
25%      9900.000000   21600.000000   27000.000000     900.000000   
50%     40500.000000   49500.000000   57600.000000   18900.000000   
75%     77400.000000   93600.000000   93600.000000   83700.000000   
max    216900.000000  215100.000000  236700.000000  254700.000000   

            lcov_31        lcov_41        lcov_42      lcov_43       lcov_52  \
count    873.000000     873.000000     873.000000    873.00000    873.000000   
mean      64.948454   13596.907216     888.659794   2847.42268    207.216495   
std     1009.205009   31925.858089    6053.890035   7614.80155   1256.161209   
min        0.000000       0.000000       0.000000      0.00000      0.000000   
25%        0.000000       0.000000       0.000000      0.00000      0.000000   
50%        0.000000       0.000000       0.000000      0.00000      0.000000   
75%        0.000000   10800.000000       0.000000      0.00000      0.

# Elevation (DEM)

Subtract the mean from the elevation values

In [ ]:
vars_elev = [i for i in vars_all if 'elev' in i]

In [58]:
vars_response = ['lst_day_mean','lst_night_mean']
vars_lst = [i for i in vars_all if 'lst' in i]
# remove vars to keep
vars_lst = [x for x in vars_lst if x not in vars_response]

In [59]:
vars_lst

['lst_day_max',
 'lst_day_min',
 'lst_day_var',
 'lst_night_max',
 'lst_night_min',
 'lst_night_var',
 'lst_day_mean_sl',
 'lst_day_max_sl',
 'lst_day_min_sl',
 'lst_day_var_sl',
 'lst_night_mean_sl',
 'lst_night_max_sl',
 'lst_night_min_sl',
 'lst_night_var_sl']

# Export to csv

In [ ]:
df.to_csv('../../data/cleaned/bal/bal_data.csv')

In [64]:
len(np.unique(df_city.y))

39

In [71]:
cell_size = 8
coords = np.unique(df_city.x), np.unique(df_city.y)
n_cells = round(len(coords[0]) / cell_size), round(len(coords[1]) / cell_size)


In [73]:
coords

(array([424996.17897104, 425496.17897104, 425996.17897104, 426496.17897104,
        426996.17897104, 427496.17897104, 427996.17897104, 428496.17897104,
        428996.17897104, 429496.17897104, 429996.17897104, 430496.17897104,
        430996.17897104, 431496.17897104, 431996.17897104, 432496.17897104,
        432996.17897104, 433496.17897104, 433996.17897104, 434496.17897104,
        434996.17897104, 435496.17897104, 435996.17897104, 436496.17897104,
        436996.17897104, 437496.17897104, 437996.17897104, 438496.17897104,
        438996.17897104, 439496.17897104, 439996.17897104, 440496.17897104]),
 array([170212.21149629, 170712.21149629, 171212.21149629, 171712.21149629,
        172212.21149629, 172712.21149629, 173212.21149629, 173712.21149629,
        174212.21149629, 174712.21149629, 175212.21149629, 175712.21149629,
        176212.21149629, 176712.21149629, 177212.21149629, 177712.21149629,
        178212.21149629, 178712.21149629, 179212.21149629, 179712.21149629,
        18

In [87]:
cutoffs_x = [coords[0][cell_size*i-1] for i in range(1,n_cells[0])] + [np.max(coords[0])]
cutoffs_y = [coords[1][cell_size*i-1] for i in range(1,n_cells[1])] + [np.max(coords[1])]

In [88]:
cutoffs_y

[173712.211496295,
 177712.211496295,
 181712.211496295,
 185712.211496295,
 189212.211496295]

In [90]:
np.searchsorted(cutoffs_y,180000)-1

2

In [95]:

for index, row in df_city.iterrows():
    print(row.x)

424996.178971041
425496.178971041
425996.178971041
426496.178971041
426996.178971041
427496.178971041
427996.178971041
428496.178971041
428996.178971041
429496.178971041
429996.178971041
430496.178971041
430996.178971041
431496.178971041
431996.178971041
432496.178971041
432996.178971041
433496.178971041
433996.178971041
434496.178971041
434996.178971041
435496.178971041
435996.178971041
436496.178971041
436996.178971041
437496.178971041
437996.178971041
438496.178971041
438996.178971041
439496.178971041
439996.178971041
440496.178971041
424996.178971041
425496.178971041
425996.178971041
426496.178971041
426996.178971041
427496.178971041
427996.178971041
428496.178971041
428996.178971041
429496.178971041
429996.178971041
430496.178971041
430996.178971041
431496.178971041
431996.178971041
432496.178971041
432996.178971041
433496.178971041
433996.178971041
434496.178971041
434996.178971041
435496.178971041
435996.178971041
436496.178971041
436996.178971041
437496.178971041
437996.1789710

In [110]:
cell_size = 8
coords = np.unique(df_city.x), np.unique(df_city.y)
n_cells = round(len(coords[0]) / cell_size), round(len(coords[1]) / cell_size)
# what are the coord cutoffs
cutoffs_x = [coords[0][cell_size*i-1] for i in range(1,n_cells[0])] + [np.max(coords[0])]    
cutoffs_y = [coords[1][cell_size*i-1] for i in range(1,n_cells[1])] + [np.max(coords[1])]
# assign a number to each of the rows as to which cell group it is in
df_city['holdout'] = None
for index, r in df_city.iterrows():
    r_ix = np.searchsorted(cutoffs_x,r.x)
    r_iy = np.searchsorted(cutoffs_y,r.y)
    df_city.loc[index, 'holdout'] = r_iy * n_cells[0] + r_ix

In [111]:
np.unique(df_city.holdout)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int64)

In [109]:
np.searchsorted(cutoffs_y,r.y+1)

0

In [104]:
coords

(array([424996.17897104, 425496.17897104, 425996.17897104, 426496.17897104,
        426996.17897104, 427496.17897104, 427996.17897104, 428496.17897104,
        428996.17897104, 429496.17897104, 429996.17897104, 430496.17897104,
        430996.17897104, 431496.17897104, 431996.17897104, 432496.17897104,
        432996.17897104, 433496.17897104, 433996.17897104, 434496.17897104,
        434996.17897104, 435496.17897104, 435996.17897104, 436496.17897104,
        436996.17897104, 437496.17897104, 437996.17897104, 438496.17897104,
        438996.17897104, 439496.17897104, 439996.17897104, 440496.17897104]),
 array([170212.21149629, 170712.21149629, 171212.21149629, 171712.21149629,
        172212.21149629, 172712.21149629, 173212.21149629, 173712.21149629,
        174212.21149629, 174712.21149629, 175212.21149629, 175712.21149629,
        176212.21149629, 176712.21149629, 177212.21149629, 177712.21149629,
        178212.21149629, 178712.21149629, 179212.21149629, 179712.21149629,
        18